#系统配置
system:
  host: "0.0.0.0"
  port: 5001
  env: debug

#looger日志
logger:
  level: info
  prefix: '[gin-admin-api]'
  director: logger
  show_line: true
  log_in_console: true

#mysql配置
mysql:
  host: 127.0.0.1
  port: 3306
  db: gin_test
  username: root
  password: 123456
  log_level: dev
  charset: utf8
  max_idle: 50